vouch:
  domains:
  - example.com
oauth:
  provider: google
  # get credentials from...
  # https://console.developers.google.com/apis/credentials
  client_id: GOOGLE_CLIENT_ID
  client_secret: GOOGLE_CLIENT_SECRET
  callback_urls: 
    - https://login.example.com/auth
  preferredDomain: example.com
